// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/scorematchingad.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pTaylorApprox
vecd pTaylorApprox(Rcpp::XPtr< CppAD::ADFun<double> > pfun, vecd x, vecd centre, vecd dynparam, size_t order);
RcppExport SEXP _scorematchingad_pTaylorApprox(SEXP pfunSEXP, SEXP xSEXP, SEXP centreSEXP, SEXP dynparamSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr< CppAD::ADFun<double> > >::type pfun(pfunSEXP);
    Rcpp::traits::input_parameter< vecd >::type x(xSEXP);
    Rcpp::traits::input_parameter< vecd >::type centre(centreSEXP);
    Rcpp::traits::input_parameter< vecd >::type dynparam(dynparamSEXP);
    Rcpp::traits::input_parameter< size_t >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(pTaylorApprox(pfun, x, centre, dynparam, order));
    return rcpp_result_gen;
END_RCPP
}
// pForward0
vecd pForward0(Rcpp::XPtr< CppAD::ADFun<double> > pfun, vecd x, vecd dynparam);
RcppExport SEXP _scorematchingad_pForward0(SEXP pfunSEXP, SEXP xSEXP, SEXP dynparamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr< CppAD::ADFun<double> > >::type pfun(pfunSEXP);
    Rcpp::traits::input_parameter< vecd >::type x(xSEXP);
    Rcpp::traits::input_parameter< vecd >::type dynparam(dynparamSEXP);
    rcpp_result_gen = Rcpp::wrap(pForward0(pfun, x, dynparam));
    return rcpp_result_gen;
END_RCPP
}
// pJacobian
vecd pJacobian(Rcpp::XPtr< CppAD::ADFun<double> > pfun, vecd x, vecd dynparam);
RcppExport SEXP _scorematchingad_pJacobian(SEXP pfunSEXP, SEXP xSEXP, SEXP dynparamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr< CppAD::ADFun<double> > >::type pfun(pfunSEXP);
    Rcpp::traits::input_parameter< vecd >::type x(xSEXP);
    Rcpp::traits::input_parameter< vecd >::type dynparam(dynparamSEXP);
    rcpp_result_gen = Rcpp::wrap(pJacobian(pfun, x, dynparam));
    return rcpp_result_gen;
END_RCPP
}
// pHessian
vecd pHessian(Rcpp::XPtr< CppAD::ADFun<double> > pfun, vecd x, vecd dynparam);
RcppExport SEXP _scorematchingad_pHessian(SEXP pfunSEXP, SEXP xSEXP, SEXP dynparamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr< CppAD::ADFun<double> > >::type pfun(pfunSEXP);
    Rcpp::traits::input_parameter< vecd >::type x(xSEXP);
    Rcpp::traits::input_parameter< vecd >::type dynparam(dynparamSEXP);
    rcpp_result_gen = Rcpp::wrap(pHessian(pfun, x, dynparam));
    return rcpp_result_gen;
END_RCPP
}
// pParameter
std::vector<bool> pParameter(Rcpp::XPtr< CppAD::ADFun<double> > pfun);
RcppExport SEXP _scorematchingad_pParameter(SEXP pfunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr< CppAD::ADFun<double> > >::type pfun(pfunSEXP);
    rcpp_result_gen = Rcpp::wrap(pParameter(pfun));
    return rcpp_result_gen;
END_RCPP
}
// pTapeJacobian
Rcpp::XPtr< CppAD::ADFun<double> > pTapeJacobian(Rcpp::XPtr< CppAD::ADFun<double> > pfun, veca1 x, veca1 dynparam);
RcppExport SEXP _scorematchingad_pTapeJacobian(SEXP pfunSEXP, SEXP xSEXP, SEXP dynparamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr< CppAD::ADFun<double> > >::type pfun(pfunSEXP);
    Rcpp::traits::input_parameter< veca1 >::type x(xSEXP);
    Rcpp::traits::input_parameter< veca1 >::type dynparam(dynparamSEXP);
    rcpp_result_gen = Rcpp::wrap(pTapeJacobian(pfun, x, dynparam));
    return rcpp_result_gen;
END_RCPP
}
// pTapeHessian
Rcpp::XPtr< CppAD::ADFun<double> > pTapeHessian(Rcpp::XPtr< CppAD::ADFun<double> > pfun, veca1 x, veca1 dynparam);
RcppExport SEXP _scorematchingad_pTapeHessian(SEXP pfunSEXP, SEXP xSEXP, SEXP dynparamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr< CppAD::ADFun<double> > >::type pfun(pfunSEXP);
    Rcpp::traits::input_parameter< veca1 >::type x(xSEXP);
    Rcpp::traits::input_parameter< veca1 >::type dynparam(dynparamSEXP);
    rcpp_result_gen = Rcpp::wrap(pTapeHessian(pfun, x, dynparam));
    return rcpp_result_gen;
END_RCPP
}
// pTapeGradOffset
Rcpp::XPtr< CppAD::ADFun<double> > pTapeGradOffset(Rcpp::XPtr< CppAD::ADFun<double> > pfun, veca1 x, veca1 dynparam);
RcppExport SEXP _scorematchingad_pTapeGradOffset(SEXP pfunSEXP, SEXP xSEXP, SEXP dynparamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr< CppAD::ADFun<double> > >::type pfun(pfunSEXP);
    Rcpp::traits::input_parameter< veca1 >::type x(xSEXP);
    Rcpp::traits::input_parameter< veca1 >::type dynparam(dynparamSEXP);
    rcpp_result_gen = Rcpp::wrap(pTapeGradOffset(pfun, x, dynparam));
    return rcpp_result_gen;
END_RCPP
}
// ptapelogdetJ
Rcpp::XPtr< CppAD::ADFun<double> > ptapelogdetJ(Rcpp::XPtr< CppAD::ADFun<double> > pfun, veca1 x, veca1 dynparam);
RcppExport SEXP _scorematchingad_ptapelogdetJ(SEXP pfunSEXP, SEXP xSEXP, SEXP dynparamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr< CppAD::ADFun<double> > >::type pfun(pfunSEXP);
    Rcpp::traits::input_parameter< veca1 >::type x(xSEXP);
    Rcpp::traits::input_parameter< veca1 >::type dynparam(dynparamSEXP);
    rcpp_result_gen = Rcpp::wrap(ptapelogdetJ(pfun, x, dynparam));
    return rcpp_result_gen;
END_RCPP
}
// swapDynamic
Rcpp::XPtr< CppAD::ADFun<double> > swapDynamic(Rcpp::XPtr< CppAD::ADFun<double> > pfun, veca1 newvalue, veca1 newdynparam);
RcppExport SEXP _scorematchingad_swapDynamic(SEXP pfunSEXP, SEXP newvalueSEXP, SEXP newdynparamSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr< CppAD::ADFun<double> > >::type pfun(pfunSEXP);
    Rcpp::traits::input_parameter< veca1 >::type newvalue(newvalueSEXP);
    Rcpp::traits::input_parameter< veca1 >::type newdynparam(newdynparamSEXP);
    rcpp_result_gen = Rcpp::wrap(swapDynamic(pfun, newvalue, newdynparam));
    return rcpp_result_gen;
END_RCPP
}
// ptapell2
Rcpp::XPtr< CppAD::ADFun<double> > ptapell2(veca1 z_ad, veca1 theta_ad, Rcpp::XPtr<llPtr> llfXPtr, transform_a1type& tran, Eigen::Matrix<int, Eigen::Dynamic, 1> fixedtheta, bool verbose);
RcppExport SEXP _scorematchingad_ptapell2(SEXP z_adSEXP, SEXP theta_adSEXP, SEXP llfXPtrSEXP, SEXP tranSEXP, SEXP fixedthetaSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< veca1 >::type z_ad(z_adSEXP);
    Rcpp::traits::input_parameter< veca1 >::type theta_ad(theta_adSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<llPtr> >::type llfXPtr(llfXPtrSEXP);
    Rcpp::traits::input_parameter< transform_a1type& >::type tran(tranSEXP);
    Rcpp::traits::input_parameter< Eigen::Matrix<int, Eigen::Dynamic, 1> >::type fixedtheta(fixedthetaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(ptapell2(z_ad, theta_ad, llfXPtr, tran, fixedtheta, verbose));
    return rcpp_result_gen;
END_RCPP
}
// getllptr
Rcpp::XPtr<llPtr> getllptr(std::string llname);
RcppExport SEXP _scorematchingad_getllptr(SEXP llnameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type llname(llnameSEXP);
    rcpp_result_gen = Rcpp::wrap(getllptr(llname));
    return rcpp_result_gen;
END_RCPP
}
// evalll
a1type evalll(Rcpp::XPtr<llPtr> ll, const veca1& u, const veca1& theta);
RcppExport SEXP _scorematchingad_evalll(SEXP llSEXP, SEXP uSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<llPtr> >::type ll(llSEXP);
    Rcpp::traits::input_parameter< const veca1& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const veca1& >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(evalll(ll, u, theta));
    return rcpp_result_gen;
END_RCPP
}
// ptapesmd
Rcpp::XPtr< CppAD::ADFun<double> > ptapesmd(veca1 u_ad, veca1 theta_ad, Rcpp::XPtr< CppAD::ADFun<double> > pll, transform_a1type& tran, manifold_a1type& man, std::string weightname, const double acut, bool verbose);
RcppExport SEXP _scorematchingad_ptapesmd(SEXP u_adSEXP, SEXP theta_adSEXP, SEXP pllSEXP, SEXP tranSEXP, SEXP manSEXP, SEXP weightnameSEXP, SEXP acutSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< veca1 >::type u_ad(u_adSEXP);
    Rcpp::traits::input_parameter< veca1 >::type theta_ad(theta_adSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr< CppAD::ADFun<double> > >::type pll(pllSEXP);
    Rcpp::traits::input_parameter< transform_a1type& >::type tran(tranSEXP);
    Rcpp::traits::input_parameter< manifold_a1type& >::type man(manSEXP);
    Rcpp::traits::input_parameter< std::string >::type weightname(weightnameSEXP);
    Rcpp::traits::input_parameter< const double >::type acut(acutSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(ptapesmd(u_ad, theta_ad, pll, tran, man, weightname, acut, verbose));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_manifolds();

static const R_CallMethodDef CallEntries[] = {
    {"_scorematchingad_pTaylorApprox", (DL_FUNC) &_scorematchingad_pTaylorApprox, 5},
    {"_scorematchingad_pForward0", (DL_FUNC) &_scorematchingad_pForward0, 3},
    {"_scorematchingad_pJacobian", (DL_FUNC) &_scorematchingad_pJacobian, 3},
    {"_scorematchingad_pHessian", (DL_FUNC) &_scorematchingad_pHessian, 3},
    {"_scorematchingad_pParameter", (DL_FUNC) &_scorematchingad_pParameter, 1},
    {"_scorematchingad_pTapeJacobian", (DL_FUNC) &_scorematchingad_pTapeJacobian, 3},
    {"_scorematchingad_pTapeHessian", (DL_FUNC) &_scorematchingad_pTapeHessian, 3},
    {"_scorematchingad_pTapeGradOffset", (DL_FUNC) &_scorematchingad_pTapeGradOffset, 3},
    {"_scorematchingad_ptapelogdetJ", (DL_FUNC) &_scorematchingad_ptapelogdetJ, 3},
    {"_scorematchingad_swapDynamic", (DL_FUNC) &_scorematchingad_swapDynamic, 3},
    {"_scorematchingad_ptapell2", (DL_FUNC) &_scorematchingad_ptapell2, 6},
    {"_scorematchingad_getllptr", (DL_FUNC) &_scorematchingad_getllptr, 1},
    {"_scorematchingad_evalll", (DL_FUNC) &_scorematchingad_evalll, 3},
    {"_scorematchingad_ptapesmd", (DL_FUNC) &_scorematchingad_ptapesmd, 8},
    {"_rcpp_module_boot_manifolds", (DL_FUNC) &_rcpp_module_boot_manifolds, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_scorematchingad(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
